# Generated by Django 4.2.5 on 2023-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonwatch',
            name='last_watched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
